import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { GoogleAnalytics } from "@next/third-parties/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <GoogleAnalytics gaId={"G-WL9QWSEE9D"} />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Source+Code+Pro:ital,wght@0,400;0,500;0,600;0,800;1,600&display=swap"
          rel="stylesheet"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta
          name="description"
          content="Web developer and UI/UX designer passionate about creating engaging websites."
        />
        <meta name="robots" content="index, follow" />
        <meta name="author" content="Jonathan Bonzali" />

        <link rel="canonical" href="https://www.iamjonathanbonzali.com/" />

        <title>Jonathan Bonzali</title>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
